export const locators = {
  breadCrumb: {
    ONE: '[data-qa="breadcrumb-1"]',
    TWO: '[data-qa="breadcrumb-2"]',
  },
  button: {
    ADD: '[data-qa="btn-add"]',
    ACTION: '[data-qa="btn-action"]',
    CONFIRM: '[data-qa="btn-confirm"]',
    COUNTDOWN: '[data-qa="btn-countdown"]',
    CREATE: '[data-qa="btn-create"]',
    CROP_DIALOG: '[data-qa="crop-dialog-btn"]',
    DONE: '[data-qa="btn-done"]',
    ENROLL: '[data-qa="btn-enroll"]',
    EXPAND: '[data-qa="btn-expand"]',
    NEXT: '[data-qa="btn-next"]',
    PROFILE: '[data-qa="btn-profile"]',
    PROGRESS: '[data-qa="btn-progress"]',
    SAVE: '[data-qa="btn-save"]',
    SAVE_BACK: '[data-qa="btn-save-back"]',
    SAVE_NEXT: '[data-qa="btn-save-next"]',
    SELECT_MATERIAL: '[data-qa="btn-select-material"]',
    SUBMIT: '[data-qa="btn-submit"]',
    TAKE_SURVEY: '[data-qa="btn-take-this-survey"]',
  },
  buttonCreate: {
    ACHIEVEMENT: '[data-qa="btn-create-achievement"]',
    NEW: '[data-qa="btn-create-new"]',
    CHANLLENGE: '[data-qa="btn-create-challenge"]',
  },
  buttonGroup: {
    CLASSPROGRAM: '[data-qa="btn-group-create-class-program"]',
  },
  buttonIcon: {
    CLOSE: '[data-qa="btn-ico-close"]',
    EDIT: '[data-qa="btn-ico-edit"]',
    DELETE: '[data-qa="btn-ico-delete"]',
    R1: '[data-qa="r1-button-icons"]',
  },
  buttonSave: {
    BACK: '[data-qa="btn-save-back"]',
  },
  card: {
    ONE: '[data-qa="card-1"]',
  },
  criteria: {
    CRITERIA: '[data-qa="criteria-1"]',
  },
  dialog: {
    DIALOG: '[data-qa="dialog"]',
    FORMDIALOG: '[data-qa="form-dialog"]',
    PDPA: '[data-qa="pdpa-dialog"]',
    WARNING: '[data-qa="dialog-warning"]',
  },
  formItem: {
    ATTACHMENT: '[data-qa="form-item-attachment"]',
    CODE: '[data-qa="form-item-code"]',
    ENROLLMENT_SETTING: '[data-qa="form-item-enrollment-setting"]',
    ENROLLMENT_PERIOD: '[data-qa="form-item-enrollment-period"]',
    NAME: '[data-qa="form-item-name"]',
    NAME_CONTENT: '[data-qa="form-item-name-content"]',
    NOTE: '[data-qa="form-item-note"]',
  },
  fragment: {
    ACHIEVEMENT: '[data-qa="fragment-achievement"]',
    ACHIEVEMENT1: '[data-qa="fragemnt-achievement-1"]',
    APPROVE_STATUS: '[data-qa="fragment-approval-status"]',
    CATEGORY_NAME: '[data-qa="fragment-category-name"]',
    CATEGORY_ID: '[data-qa="fragment-category-id"]',
    CRITERIA: '[data-qa="fragment-criteria"]',
    DATE_TIME: '[data-qa="fragment-date-time-picker"]',
    ENROLLMENT_PERIOD: '[data-qa="fragment-enrollment-period"]',
    PLAY_BOX: '[data-qa="fragment-gamification-play-box"]',
    TOTAL: '[data-qa="fragment-total"]',
    SEARCH: '[data-qa="fragment-search"]',
    RESULT: '[data-qa="fragment-result"]',
  },
  ico: {
    CHRIGHT: '[data-qa="ico-chevron-right"]',
    DELETE: '[data-qa="ico-delete"]',
  },
  input: {
    ANSWER: '[data-qa="input-answer"]',
    NUMBER: '[data-qa="input-number"]',
    TEXT: '[data-qa="input-text"]',
  },
  identity: {
    COURSE: '[data-qa="course-identity"]',
    CLASS: '[data-qa="class-identity"]',
    MATERIAL: '[data-qa="material-identity"]',
    PATHWAY: '[data-qa="pathway-identity"]',
  },
  switch: {
    PUBLISH: '[data-qa="switch-publish"]',
  },
  panelCard: {
    GAMI: '[data-qa="panel-card-gamification"]',
  },
  question: {
    NUBMER: '[data-qa="question-number"]',
  },
  panel: {
    SCHEDULE: '[data-qa="panel-card-schedule"]',
  },
  row1: {
    ACHIEVEMENT: '[data-qa="r1-txt-achievement"]',
    ACHIEVEMENT_NAME: '[data-qa="r1-txt-achievement-name"]',
    ADMIN: '[data-qa="r1-administrator"]',
    CODE: '[data-qa="r1-txt-code"]',
    NAME: '[data-qa="r1-txt-name"]',
    POINT: '[data-qa="r1-point"]',
    PUBLISH: '[data-qa="r1-ico-publish"]',
  },
  select: {
    ACCOUNT: '[data-qa="select-account"]',
  },
  section: {
    MATERIAL: '[data-qa="section-material"]',
    NAME: '[data-qa="section-name"]',
  },
  slot: {
    MATERIAL: '[data-qa="material-slot"]',
  },
  tab: {
    ADMIN: '[data-qa="tab-administrator"]',
    HIGHLIGHT: '[data-qa="tab-highlight"]',
  },
  txt: {
    AMOUNT: '[data-qa="txt-amount"]',
    APPROVE_STATUS: '[data-qa="txt-approval-status"]',
    BUTTON: '[data-qa="txt-btn"]',
    DESC: '[data-qa="txt-desc"]',
    NAME: '[data-qa="txt-name"]',
    ID: '[data-qa="txt-id"]',
    POINT: '[data-qa="txt-total-point"]',
    PROGRESS_STATUS: '[data-qa="txt-progress-status"]',
    TITLE: '[data-qa="txt-title"]',
    TOTAL_ACHIEVEMENT: '[data-qa="txt-total-achievement"]',
    VAL: '[data-qa="txt-val"]',
  },
  txtField: {
    CODE: '[data-qa="txt-field-code"]',
    NAME: '[data-qa="txt-field-name"]',
    NAME_CONTENT: '[data-qa="txt-field-name-content"]',
    DESC: '[data-qa="txt-field-desc"]',
    NOTE: '[data-qa="txt-field-note"]',
    SEARCH: '[data-qa="txt-field-search"]',
    TXT_FIELD: '[data-qa="txt-field"]',
  },
};
