export const el: Record<string, string> = {
  logo: '[data-testid="nocnoc-logo"]',
  homepage: ".home-page",
  fragmentSearch: '[data-testid="search-btn"]',
  btnCart: '[data-testid="cart-btn"]',
  btnLogin: '[data-testid="login-btn"]',
  btnLang: '[data-testid="language-btn"]',
  btnMenu: '[data-testid="menu-btn"]',
  menuSideLeft: "#modal .main-nav.header-panel",
  allMenuList: ".DeptNavDropdown-grid .columno3",
  new: "body .ins-preview-wrapper",
  fragmentRecommend: '[data-testid="recommend-section"]',
  inputLogin: "#email-phone",
  loginInputSection: ".login-landing-page",
  loginOtpSection: ".otp-login-page",
  loginPasswordSection: ".login-with-password-page",
  btnLoginSubmit: ".login-landing-page > button",
  productDetailPage: "main.product-details",
  fragmentProductDetail: "#product-overview-section",
  fragmentPrice: '[data-testid="final-price-per-unit"]',
  fragmentProductTab: "#product-tab-section",
  btnAddToCart: "#cartItems-add-to-cart",
  dialogSummaryAddToCart: "#modal > div:nth-child(2)",
  fragmentConfirmPrice: '[data-testid="final-price-confirmation"]',
  btnCancelSummary: "#modal > div:nth-child(2) button:nth-child(1)",
  btnConfirmSummary: "#modal > div:nth-child(2) button:nth-child(2)",
  cartPage: "main.cart-listing",
};
